/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Amigo;
import model.Emprestimo;
import model.Ferramenta;

/**
 *
 * @author denise
 */
public class FrmGerenciarEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form FrmaGerenciarEmprestimo
     */
    private Emprestimo objetoemprestimo;
    private Amigo objetoamigo;
    private Ferramenta objetoferramenta;
    private Integer idemprestimo;
    
    public FrmGerenciarEmprestimo() {
        initComponents();
        this.objetoemprestimo = new Emprestimo(); // carrega objetoaluno de aluno
        this.objetoamigo = new Amigo(); // carrega objetoaluno de aluno
        this.objetoferramenta = new Ferramenta(); // carrega objetoaluno de aluno
        this.carregaTabela();
        jBDevolver.setVisible(false);
    }
    
    public void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) this.jTEmprestimos.getModel();
        modelo.setNumRows(0); //Posiciona na primeira linha da tabela
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        //sdf.format(date);
        Integer filtro = jCFiltroExibir.getSelectedIndex();
        System.out.println("filtro " + filtro);
//Carrega a lista de objetos aluno
        ArrayList<Emprestimo> minhalista = objetoemprestimo.getMinhaLista();
        for (Emprestimo a : minhalista) {
            String dtdev = null;
            try {
                dtdev = sdf.format(a.getDataDevolucao());
            } catch (Exception e) {
            }
            if ((filtro == 0)
                    || (filtro == 1 && dtdev == null)
                    || (filtro == 2 && dtdev != null)) {
                
                modelo.addRow(new Object[]{
                    a.getId(),
                    objetoamigo.getNomeById(a.getIdAmigo()),
                    objetoferramenta.getNomeById(a.getIdFerramenta()),
                    sdf.format(a.getDataEmprestimo()),
                    sdf.format(a.getDataPrevDevolucao()),
                    dtdev,
                    a.getStatus()
                });
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBDevolver = new javax.swing.JButton();
        jCFiltroExibir = new javax.swing.JComboBox<>();
        jButtonFiltrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTEmprestimos = new javax.swing.JTable();
        JLgerenciamentoemprestimo = new javax.swing.JLabel();

        setTitle("Gerenciamento de Emprestimos");

        jPanel1.setBackground(new java.awt.Color(54, 144, 255));

        jBDevolver.setText("Devolver Ferramenta");
        jBDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDevolverActionPerformed(evt);
            }
        });

        jCFiltroExibir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos Emprestimos", "Ferramentas Não Devolvidas", "Ferramentas Devolvidas" }));
        jCFiltroExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCFiltroExibirActionPerformed(evt);
            }
        });

        jButtonFiltrar.setText("Filtrar");
        jButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarActionPerformed(evt);
            }
        });

        jTEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Amigo", "Ferramenta", "Data Emprestimo", "Data Prev. Devolução", "Data Devolução", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTEmprestimos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTEmprestimosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTEmprestimos);
        if (jTEmprestimos.getColumnModel().getColumnCount() > 0) {
            jTEmprestimos.getColumnModel().getColumn(0).setMaxWidth(50);
            jTEmprestimos.getColumnModel().getColumn(6).setResizable(false);
        }

        JLgerenciamentoemprestimo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JLgerenciamentoemprestimo.setText("Gerenciamento de Emprestimos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCFiltroExibir, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(JLgerenciamentoemprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLgerenciamentoemprestimo)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCFiltroExibir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFiltrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDevolver)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDevolverActionPerformed
        try {
            // validando dados da interface gráfica.
            int id = 0;
            if (this.jTEmprestimos.getSelectedRow() == -1) {
                throw new Mensagens("Selecione uma ferramenta não devolvida");
            } else {
                id = Integer.parseInt(this.jTEmprestimos.
                    getValueAt(this.jTEmprestimos.getSelectedRow(), 0).
                    toString());
            }
            // retorna 0 -> primeiro botão | 1 -> segundo botão | 2 -> terceiro botão
            int respostaUsuario = JOptionPane.
            showConfirmDialog(null,
                "Tem certeza que deseja devolver esta Ferramenta ?");
            if (respostaUsuario == 0) {// clicou em SIM
                objetoemprestimo.devolver(this.idemprestimo);
                carregaTabela();
                jBDevolver.setVisible(false);
            }

        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            // atualiza a tabela.
            carregaTabela();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jBDevolverActionPerformed

    private void jButtonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarActionPerformed
        // TODO add your handling code here:
        carregaTabela();
    }//GEN-LAST:event_jButtonFiltrarActionPerformed

    private void jTEmprestimosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTEmprestimosMouseClicked
        // TODO add your handling code here:
        jBDevolver.setVisible(false);
        int row = this.jTEmprestimos.getSelectedRow();
        if (row != -1) {
            idemprestimo = Integer.parseInt(this.jTEmprestimos.getValueAt(row, 0).toString());
            String Status = this.jTEmprestimos.getValueAt(row, 6).toString();
            if (Status.equals("Emprestado")) {
                jBDevolver.setVisible(true);
            }
            //String telefone = this.jTEmprestimos.getValueAt(row, 2).toString();
            //String email = this.jTEmprestimos.getValueAt(row, 3).toString();
            //this.jTFNome.setText(nome);
            //this.jTFTelefone.setText(telefone);
            //this.jTFEmail.setText(email);
        }
    }//GEN-LAST:event_jTEmprestimosMouseClicked

    private void jCFiltroExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCFiltroExibirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCFiltroExibirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGerenciarEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLgerenciamentoemprestimo;
    private javax.swing.JButton jBDevolver;
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JComboBox<String> jCFiltroExibir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTEmprestimos;
    // End of variables declaration//GEN-END:variables
}
